### ISSUE TITLE
[PE-D][Tester D] Grades only allow single letter

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W17-3/tp#145]
![image.png](https://raw.githubusercontent.com/lyuting47/ped/main/files/661ba134-751c-45fd-b11b-09caff77cbb4.png)

NUS has many other valid letter grades such as A+, B-. Being unable to enter these is quite inconvenient for the tutor.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: lyuting47/ped#5

**Comment by heyzec** [comment]
Makes sense, given that our app is in the context of NUS.
