### ISSUE TITLE
[PE-D][Tester E] Find command invalid inputs

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W17-3/tp#151]
Find command allows each field to be specified multiple times. For example, no error is thrown when name keyword is provided twice. Matching is only done with the second keyword, which is probably not the intended behaviour

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ryanguai/ped#6

**Comment by heyzec** [comment]
Actually, our UG did specify the behaviour when there are multiple prefixes.
![image](https://user-images.githubusercontent.com/61238538/199019920-762e6ad0-339c-4c2d-8d82-b5b8f104087e.png)
