### ISSUE TITLE
[PE-D][Tester D] Tutorial can be added on same day and venue with overlapping timing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W17-3/tp#155]
![image.png](https://raw.githubusercontent.com/lyuting47/ped/main/files/4ed84dde-3d90-4e4a-b0e4-8d689fea7904.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: lyuting47/ped#6

**Comment by heyzec** [comment]
Also see #161
