### ISSUE TITLE
[PE-D][Tester B] Missing other possible prefixes in the documentation for edit student.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W17-3/tp#172]
![image.png](https://raw.githubusercontent.com/Hongyi6328/ped/main/files/df7c275a-271b-49b1-9258-ef363c5fba67.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Hongyi6328/ped#5

**Comment by heyzec** [comment]
Fixed. https://github.com/AY2223S1-CS2103T-W17-3/tp/commit/370014ba80aad78dbcb41caf4709ffdf9e4d2f84
