### ISSUE TITLE
[PE-D][Tester B] Leading 0 in attendance

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W17-3/tp#176]
![image.png](https://raw.githubusercontent.com/Hongyi6328/ped/main/files/0db43bbf-8135-4364-a9f4-c269056bcbdf.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: Hongyi6328/ped#6

**Comment by heyzec** [comment]
Also remember to change for participation!
