### ISSUE TITLE
[PE-D][Tester B] Cannot find the expected students given two prefixes.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W17-3/tp#183]
How to reproduce:
1. `clear f/student
1. `add student n/John Doe i/A0000000J ph/98765432 e/johnd@example.com tele/johnDoe m/CS2103T tut/W17`
2. `add student n/Betsy Crowe i/A0000000B t/struggling e/betsycrowe@example.com ph/91234567 tele/betsy_crowe m/CS2105 tut/G03 att/3 part/1 g/C t/quiet`
4. `find n/Doe m/CS2105`

![image.png](https://raw.githubusercontent.com/Hongyi6328/ped/main/files/61b370d1-2759-471b-b146-710a321570cd.png)

This contradicts to what is said in the UG.

![image.png](https://raw.githubusercontent.com/Hongyi6328/ped/main/files/d53204c8-650c-4175-b059-00a2d6d07154.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Hongyi6328/ped#8

**Comment by yeoyujie** [comment]
User Guide was not clear. The OR search here refers to the persons matching at least one keyword in name fields, but across prefixes it is an AND search.
