### ISSUE TITLE
[PE-D][Tester D] Resizing window makes some components completely invisible

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W17-3/tp#189]
![image.png](https://raw.githubusercontent.com/lyuting47/ped/main/files/94602744-fb88-48f6-b1b4-275088740f97.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: lyuting47/ped#14

**Comment by heyzec** [comment]
Not an issue. Let's set a minimum window dimension to "fix" this.
